### ISSUE TITLE
experiment_runner.py bombs in REU_2018_Search When it calls server.run_server()

### ISSUE THREAD

**Issue by Kmccabe** [gmucsn/mTree#13]
RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING RUNNING 
 * Debugger is active!
 * Debugger PIN: 112-985-403
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\flask_socketio\__init__.py", line 505, in run_server
    eventlet_socket = eventlet.listen(addresses[0][4], addresses[0][0])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\eventlet\convenience.py", line 78, in listen
    sock.bind(addr)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by skunath** [comment]
It looks like you might already have a process running. Can you make sure that it's the only experiment running?

**Comment by Kmccabe** [comment]
That was the problem.  It seems the server keeps running even after I closed python.  I had to restart my computer.  Once the server is running how do I access it.  I assume it is 127.0.0.1:5000/something.
