### ISSUE TITLE
mTree shutting down experiment and actor system, regardless of experiment running.

### ISSUE THREAD

**Issue by tomwangth** [gmucsn/mTree#20]
Here is the guess game example in the primer:

CREATING ACTOR SYSteMS
environment started...

Guessing Game Experiment

send init message
institution started
agent created
send start message
EXPERIMENT SHUTTING DOWN
..... Initialize Agent
..... Initialize Institution
..... Start Experiment
ACTOR SYSTEM SHOULD HAVE SHUTDOWN

And another instance when we run our simulation:

Toms-MacBook-Pro:mes TW$ python3 collateral_game_controller_temp.py
CREATING ACTOR SYSteMS

Collateral Game Simulation

game initiated by the experimenter
start message sent to the environment...
Initializing environment ...
EXPERIMENT SHUTTING DOWN
alex is watcing you, steve!
ACTOR SYSTEM SHOULD HAVE SHUTDOWN

**Comment by skunath** [comment]
Can you push your experiment code up so that I can see?

**Comment by tomwangth** [comment]
pushed

**Comment by skunath** [comment]
I've updated a couple of things. You'll need to get the updated version of mTree.

The big thing will be that in order to run a simulation you'll just use the following:
mTree_runner -i ./config/basic_simulation.json

The log file will be large if there is a problem. You'll need to trace back to the first exception it finds. That should then tell you what line to debug.

I'll be in tomorrow and can help as well.

**Comment by tomwangth** [comment]
We tried running it. Turne out the command is not found.

**Comment by skunath** [comment]
This isn't a helpful comment.

What system did you try on? What command did you use? What directory were you in? Did you update mTree appropriately? Did you check the mtree repo bin directory?

**Comment by tomwangth** [comment]
So we run it both on mac and windows in the REU_2019 mes directory. Here are a few commands we tried. I believe we updated mTree the same way a couple of days ago.

Toms-MacBook-Pro:mes TW$ mTree_runner -i ./config/basic_simulation.json collateral_game_controller_temp.py
-bash: mTree_runner: command not found
Toms-MacBook-Pro:mes TW$ mTree_runner -i ./config/basic_simulation.json
-bash: mTree_runner: command not found

**Comment by skunath** [comment]
Okay. That's better.

Can you also go into the mtree repo directory and reinstall it?
pip install -e .

**Comment by tomwangth** [comment]
Okay. Reinstalled mTree.

Toms-MacBook-Pro:REU_2019_Simulations TW$ mTree_runner -i ./config/basic_simulation.json
mTree Runner
Traceback (most recent call last):
  File "/anaconda3/bin/mTree_runner", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/repos/mTree/bin/mTree_runner", line 37, in <module>
    main(sys.argv[1:])
  File "/repos/mTree/bin/mTree_runner", line 33, in main
    mtree_runner = Runner(inputfile)
  File "/repos/mTree/mTree/runner/runner.py", line 20, in __init__
    self.configuration = self.load_mtree_config(config_file)
  File "/repos/mTree/mTree/runner/runner.py", line 27, in load_mtree_config
    with open(config_file) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: './config/basic_simulation.json'

**Comment by skunath** [comment]
Boo. I've probably got that commit staged on my laptop.

Well, all you'll need to do is create a config direction and then create a json file.

The json file would be like:
{"mtree_type": "mes_simulation_description",
  "name":"Basic Test",
"id": "0a31f5be-92ab-11e9-8313-da001988a901", "environment": "<PUT THE NAME OF THE ENVIRONMENT CLASS HERE>", "institution": "<PUT THE NAME OF THE INSTITUTION CLASS HERE>", "agents": [{"agent_name": "<PUT THE NAME OF THE AGENT CLASS HERE>", "number": 1}, {"agent_name": "<PUT THE NAME OF THE AGENT CLASS HERE>", "number": 1}]}

save that as basic_simulation.json

Then try to run.

**Comment by skunath** [comment]
For some reason it didn't capture my changes in the last comment. You need to fill in the class names for your agents, institutions, agents. So next to each of those fields in the json doc, put the name of the classes in.

**Comment by tomwangth** [comment]
Toms-MacBook-Pro:REU_2019_Simulations TW$ mTree_runner -i ./config/basic_simulation.json
mTree Runner
Runner
Current Configuration:  {
    "agents": [
        {
            "agent_name": "CollateralBorrower",
            "number": 1
        },
        {
            "agent_name": "CollateralLender",
            "number": 1
        }
    ],
    "environment": "CollateralEnvironment",
    "id": "0a31f5be-92ab-11e9-8313-da001988a901",
    "institution": "CollateralInstitution",
    "mtree_type": "mes_simulation_description",
    "name": "Basic Test"
}
<module 'mes.collateral_game_borrower' from './mes/collateral_game_borrower.py'>
<module 'mes.collateral_game_institution' from './mes/collateral_game_institution.py'>
<module 'mes.collateral_game_lender' from './mes/collateral_game_lender.py'>
<module 'mes.collateral_game_environment' from './mes/collateral_game_environment.py'>
CREATING ACTOR SYSteMS
Actor system Started
CREATING AN ENVIRONMENT
ActorAddr-/A~a
start message sent to the environment...
alex is watcing you, steve!
alex is watcing you, steve!
alex is watcing you, steve!
EXPERIMENT SHUTTING DOWN
ACTOR SYSTEM SHOULD HAVE SHUTDOWN

**Comment by skunath** [comment]
Is there a point to this last comment?

**Comment by rfraser4** [comment]
There's an issue where the setting the sender does not seem to work. In the debug it's printing the else and the statement before.

![steve issue](https://user-images.githubusercontent.com/47042204/61299054-62c88500-a7ad-11e9-8866-5ee82680a083.PNG)

**Comment by rfraser4** [comment]
Also mTree doesn't use the log folder. Just puts it in the REU_2019_Simulations folder containing mes folder.

**Comment by skunath** [comment]
Can you post the relevant code?

The log folder thing is a known issue. I thought we had discussed how the
experiment log would be on the EXPERIMENT lines of the mtree.log

**Comment by rfraser4** [comment]
![steve issue](https://user-images.githubusercontent.com/47042204/61310191-ce1c5200-a7c1-11e9-8dde-7bac5ebe9c7b.PNG)

Here it is. The debug statements don't work in the if and elif.

**Comment by skunath** [comment]
When are you setting self.debug? Are you trying to inject the property?

**Comment by rfraser4** [comment]
self. debug is set to true in the __init__. Not injecting the property, just trying to get the sender of the message on line 160.
